### ISSUE TITLE
Create basic client-side routing

### ISSUE THREAD

**Issue by Alokym** [Alokym/symphony-words#2]
Routes:
/ - main view
/create - view for creating vocabulary
/find - view for entering vocabulary id
/learn/{vocabularyId} - view for learning words.

By default, user should be navigated to the main view.
Creating specific views/functionality is out of scope of this issue. Temporary view caps would be enough

**Comment by vstukanov** [comment]
At this moment I rename a `/learn` endpoint with `/find` for entering vocabulary id view.

**Comment by Alokym** [comment]
Makes sense. Updated initial description
